# Generated by Django 3.2.8 on 2021-11-15 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211114_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='p_category',
        ),
    ]
