# Generated by Django 3.2.8 on 2021-11-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('age', 'age')], max_length=200),
        ),
    ]
