# Generated by Django 3.2.8 on 2021-11-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_variation_variation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='image_three',
            field=models.ImageField(default=None, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images_one',
            field=models.ImageField(default=None, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images_two',
            field=models.ImageField(default=None, upload_to='images/products'),
        ),
    ]
