# Generated by Django 3.2.8 on 2021-11-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211121_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_three',
            field=models.ImageField(upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images_two',
            field=models.ImageField(upload_to='images/products'),
        ),
    ]
