# Generated by Django 3.2.8 on 2021-11-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211121_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_three',
            field=models.ImageField(null=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images_one',
            field=models.ImageField(null=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images_two',
            field=models.ImageField(null=True, upload_to='images/products'),
        ),
    ]
