# Generated by Django 3.2.8 on 2021-11-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211121_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_three',
            new_name='images_three',
        ),
    ]
