# Generated by Django 3.2.8 on 2021-11-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_image_three_product_images_three'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
