# Generated by Django 3.2.8 on 2021-11-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images_one',
            field=models.ImageField(blank=True, default=1, upload_to='images/products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='images_three',
            field=models.ImageField(blank=True, default=1, upload_to='images/products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='images_two',
            field=models.ImageField(blank=True, default=1, upload_to='images/products'),
            preserve_default=False,
        ),
    ]
