# Generated by Django 3.2.8 on 2021-12-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('store', '0001_initial'),
        ('category', '0003_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
