# Generated by Django 3.2.8 on 2021-12-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_coupon_redeemedcoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_name',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
    ]
