# Generated by Django 3.2.8 on 2021-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='userprofile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
