# Generated by Django 3.2.8 on 2021-11-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211127_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='userprofile'),
        ),
    ]
