# Generated by Django 3.2.8 on 2021-11-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='userprofile'),
        ),
    ]
