# Generated by Django 3.2.8 on 2021-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('completed', 'completed'), ('cancelled', 'cancelled')], max_length=200),
        ),
    ]
