# Generated by Django 3.2.8 on 2021-11-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Order Accepted', 'Order Accepted'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Deliverd', 'Deliverd'), ('cancelled', 'cancelled')], max_length=200),
        ),
    ]
