# Generated by Django 3.2.8 on 2021-11-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Accepted', '1'), ('Shipped', '2'), ('Out For Delivery', '3'), ('Deliverd', '4'), ('cancelled', 'cancelled')], max_length=200),
        ),
    ]
