# Generated by Django 3.2.8 on 2021-11-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Order Accepted'), (2, 'Shipped'), (3, 'Out For Delivery'), (4, 'Deliverd'), (0, 'cancelled')], max_length=200),
        ),
    ]
