# Generated by Django 3.2.8 on 2021-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Order Accepted'), (2, 'Shipped'), (3, 'Out For Delivery'), (4, 'Deliverd'), (0, 'cancelled')], default=1),
        ),
    ]
