# Generated by Django 3.2.8 on 2021-11-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.IntegerField(choices=[(1, 'Order Accepted'), (2, 'Shipped'), (3, 'Out For Delivery'), (4, 'Deliverd'), (0, 'cancelled')], default=1),
        ),
    ]
