# Generated by Django 3.2.8 on 2021-12-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderproduct_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('paypal', 'paypal'), ('rezorpay', 'rezorpay')], max_length=200),
        ),
    ]
