# Generated by Django 3.2.8 on 2021-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('paypal', 'paypal'), ('rezorpay', 'rezorpay')], default='cash_on_delivery', max_length=200),
        ),
    ]
